### ISSUE TITLE
Constant crash. Memory management issue.

### ISSUE THREAD

**Issue by Krivoblotsky** [philippec/PhFacebook#47]
I'm experiencing the constant EXC_BAD_ACCESS crash when using PhFacebook in PhAuthenticationToken. 

![shot](https://cloud.githubusercontent.com/assets/1411778/8637811/3fc818dc-28ad-11e5-88b8-52b01a4b79ab.png)

After I've investigated the source, I've found that you keep "expiry" as "assign" property, which means the retainCount will not be increased. Next you are setting [NSDate dateWithTimeIntervalSinceNow: seconds] which is already "autoreleased" object, so when dealloc is called you are trying to release _expiry again, that's cause the issue. 

``` objc
....
@property (nonatomic, readonly) NSDate *expiry;
....
[_expiry release];
...
```

Can you, please, refactor the property to have "retain" attribute? Or even refactor the whole class to use property attributes, and get rid of [token copy] and [_permissions copy] in constructor.

...or just add "retain":

``` objc
_expiry = [[NSDate dateWithTimeIntervalSinceNow: seconds] retain];
```

I can submit a pull request if you want.

**Comment by philippec** [comment]
That looks like a weird oversight on my part and is now fixed. Thanks!

As for refactoring the properties to be explicitly retain or copy, I don't think there is a need because they are declared as readonly. The naked ivar access done in -init and -dealloc is correct (now), and remains an implementation detail as far as the calling class goes.
